uint64[] joint_id
float64[] final_position
uint64[] number_steps
float64[] time
string interpolation_method
float64[] final_velocity
#JointLinearInterpolationParameters[] wb_joints_parameters
---
bool success
string status_message
